### ISSUE TITLE
593c190 broke stdout printing for depsolve command

### ISSUE THREAD

**Issue by atodorov** [weldr/bdcs#121]
Commit 593c190 broke the depsolve command, more precisely printing the list of dependencies on stdout. I did some debugging breaking on the line
`Right assignments -> mapM_ TIO.putStrLn assignments`

When executing `mapM_ TIO.putStrLn assignments` inside ghci it does print a list of RPMs but when the bdcs-depsolve command is called it prints nothing! From what I can tell depsolving is working fine it just doesn't print anything on stdout.

I've also tried with depsolve.hs before that commit was applied and it also works fine and prints the results on the console.

**Comment by clumens** [comment]
What are you importing into the database, and what command line are you using for depsolve?

**Comment by clumens** [comment]
Nevermind, I see.
