### ISSUE TITLE
depclose tests failed

### ISSUE THREAD

**Issue by atodorov** [weldr/bdcs#56]
@bcl @clumens the Haskell depclose also started failing today (despite the PR producing PASS result). 

In Travis I get 'AssertionError: u'atlas' not found in ''' which points to empty depclose output. However locally I get:

```
depclose: SQLite3 returned ErrorError while attempting to perform prepare "SELECT DISTINCT \"group_key_values\".\"group_id\", \"key_val\".\"ext_value\"\nFROM \"key_val\" INNER JOIN \"group_key_values\" ON \"key_val\".\"id\" = \"group_key_values\".\"key_val_id\"\nWHERE (\"key_val\".\"key_value\" = ?) AND (\"key_val\".\"val_value\" = ?)\n": no such table: key_val
```

can you advise what has changed ?

**Comment by clumens** [comment]
I pushed a PR that changed the database layout somewhat.  If this test is running against the side db you've got, you need to regenerate it with the latest version of the importer.

**Comment by atodorov** [comment]
Yeah, that's blocked by the 
```
import: /rpms/repodata/repomd.xml: openBinaryFile: does not exist (No such file or directory)
import: ParseError {errorContexts = [], errorMessage = "Failed reading: takeWhile1", errorPosition = 1:1}
Makefile:26: recipe for target 'mddb' failed
```

error. I'll see if I can workaround somehow locally.

**Comment by atodorov** [comment]
ok, I think the last one is b/c importer can't automatically figure out the path to primary.xml.gz. Has this changed somehow ?

**Comment by atodorov** [comment]
Closing. Manually updated the existing DB and another bug related to import URLs without slashes has been fixed meanwhile.
